// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Chart from 'stimulus-chartjs'
application.register('chart', Chart)

import ExpenseController from "./expense_controller"
application.register("expense", ExpenseController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
